// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package iter

// OptionForInt can hold an int value or not.
type OptionForInt struct {
	value  int
	isNone bool
}

// SomeInt returns an Option holding an int value.
func SomeInt(value int) OptionForInt {
	return OptionForInt{value: value, isNone: false}
}

// NoneInt returns an Option holding no int value.
func NoneInt() OptionForInt {
	return OptionForInt{isNone: true}
}

func (o OptionForInt) IsSome() bool {
	return !o.isNone
}

func (o OptionForInt) IsNone() bool {
	return o.isNone
}

func (o OptionForInt) Expect(msg string) int {
	if o.isNone {
		panic(msg)
	}

	return o.value
}

func (o OptionForInt) ExpectNone(msg string) {
	if !o.isNone {
		panic(msg)
	}
}

func (o OptionForInt) Unwrap() int {
	return o.Expect("Called `Unwrap` on a `None` Option.")
}

func (o OptionForInt) UnwrapOr(defaultValue int) int {
	if o.isNone {
		return defaultValue
	}

	return o.value
}

func (o OptionForInt) UnwrapOrElse(f func() int) int {
	if o.isNone {
		return f()
	}

	return o.value
}

func (o OptionForInt) UnwrapNone() {
	o.ExpectNone("Called `UnwrapNone` on a `Some` value")
}

// OptionForString can hold an string value or not.
type OptionForString struct {
	value  string
	isNone bool
}

// SomeString returns an Option holding an string value.
func SomeString(value string) OptionForString {
	return OptionForString{value: value, isNone: false}
}

// NoneString returns an Option holding no string value.
func NoneString() OptionForString {
	return OptionForString{isNone: true}
}

func (o OptionForString) IsSome() bool {
	return !o.isNone
}

func (o OptionForString) IsNone() bool {
	return o.isNone
}

func (o OptionForString) Expect(msg string) string {
	if o.isNone {
		panic(msg)
	}

	return o.value
}

func (o OptionForString) ExpectNone(msg string) {
	if !o.isNone {
		panic(msg)
	}
}

func (o OptionForString) Unwrap() string {
	return o.Expect("Called `Unwrap` on a `None` Option.")
}

func (o OptionForString) UnwrapOr(defaultValue string) string {
	if o.isNone {
		return defaultValue
	}

	return o.value
}

func (o OptionForString) UnwrapOrElse(f func() string) string {
	if o.isNone {
		return f()
	}

	return o.value
}

func (o OptionForString) UnwrapNone() {
	o.ExpectNone("Called `UnwrapNone` on a `Some` value")
}

// OptionForUint can hold an uint value or not.
type OptionForUint struct {
	value  uint
	isNone bool
}

// SomeUint returns an Option holding an uint value.
func SomeUint(value uint) OptionForUint {
	return OptionForUint{value: value, isNone: false}
}

// NoneUint returns an Option holding no uint value.
func NoneUint() OptionForUint {
	return OptionForUint{isNone: true}
}

func (o OptionForUint) IsSome() bool {
	return !o.isNone
}

func (o OptionForUint) IsNone() bool {
	return o.isNone
}

func (o OptionForUint) Expect(msg string) uint {
	if o.isNone {
		panic(msg)
	}

	return o.value
}

func (o OptionForUint) ExpectNone(msg string) {
	if !o.isNone {
		panic(msg)
	}
}

func (o OptionForUint) Unwrap() uint {
	return o.Expect("Called `Unwrap` on a `None` Option.")
}

func (o OptionForUint) UnwrapOr(defaultValue uint) uint {
	if o.isNone {
		return defaultValue
	}

	return o.value
}

func (o OptionForUint) UnwrapOrElse(f func() uint) uint {
	if o.isNone {
		return f()
	}

	return o.value
}

func (o OptionForUint) UnwrapNone() {
	o.ExpectNone("Called `UnwrapNone` on a `Some` value")
}
