// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package iter

// VectorOfInt builds an Iterator from a slice.
func VectorOfInt(slice []int) IteratorForInt {
	return IteratorForInt{
		iter: &vectorForInt{slice: slice, cursor: 0},
	}
}

type vectorForInt struct {
	slice  []int
	cursor uint
}

func (v *vectorForInt) Next() OptionForInt {
	if v.cursor >= uint(len(v.slice)) {
		return NoneInt()
	}

	item := v.slice[v.cursor]
	v.cursor++

	return SomeInt(item)
}

var _ IterableForInt = &vectorForInt{}

// VectorOfString builds an Iterator from a slice.
func VectorOfString(slice []string) IteratorForString {
	return IteratorForString{
		iter: &vectorForString{slice: slice, cursor: 0},
	}
}

type vectorForString struct {
	slice  []string
	cursor uint
}

func (v *vectorForString) Next() OptionForString {
	if v.cursor >= uint(len(v.slice)) {
		return NoneString()
	}

	item := v.slice[v.cursor]
	v.cursor++

	return SomeString(item)
}

var _ IterableForString = &vectorForString{}
